### ISSUE TITLE
Status Tracking

### ISSUE THREAD

**Issue by f4814** [CyberSchoolSystem/CyberSchoolSystem-server#1]
- [x] Database
  - [x] Get Running in Haskell
  - [x] Define Table Layout

----

- [x] API
  - [x] Basic Voting (+ manipulation)
    - [x] Vote timing
  - [x] Basic access control
    - [x] Export
  - [x] Return JSON Types
  - [x] Docs

----

- [x] Management
  - [x] API
    - [x] Manipulate Votes
    - [x] Manipulate Citizens
    - [x] Manipulate Access
    - [x] Stats
    - [x] Change password
  - [x] Authentication
  - [x] ACL
  - [x] User search class filter
 
---

- [ ] ~~Testsuite~~ (¯\_(ツ)_/¯ )

---

- [x] Frontend
  - [x] Vote Page for citizens
  - [x] Customs Page for entrance control
  - [x] Customs Page for exit control
  - [x] Implement Pie Charts
  - [x] Custom Page Data Export of Access control
  - [x] Custom page add Vote (interactive)
  - [x] Change password
